/** @type {import('../scripts/themeSafety.mjs', { with: { 'resolution-mode': 'import' } }).ThemeSafetyContract} */
const themeSafetyContract = {
  background: 'ui:surface.canvas',
  contrast: [
    {
      id: 'readable-primary',
      metric: 'wcag',
      minimum: 4.5,
      roles: ['ui:text.primary', 'terminal:foreground'],
    },
    {
      id: 'readable-supporting-ui',
      metric: 'wcag',
      minimum: 4.5,
      roles: [
        'ui:text.secondary',
        'ui:text.muted',
        'ui:text.chrome',
        'ui:text.sidebar',
        'ui:text.status',
      ],
    },
    {
      id: 'readable-plain-code',
      metric: 'apca',
      minimum: 70,
      roles: ['syntax:variable'],
    },
    {
      id: 'readable-code',
      metric: 'apca',
      minimum: 45,
      roles: [
        'syntax:control',
        'syntax:function',
        'syntax:type',
        'syntax:data',
        'syntax:string',
        'syntax:literal',
        'syntax:emphasis',
        'syntax:file',
      ],
    },
    {
      id: 'readable-structure',
      metric: 'apca',
      minimum: 40,
      roles: ['syntax:declaration'],
    },
    {
      id: 'readable-quiet',
      metric: 'apca',
      minimum: 30,
      roles: ['syntax:comment', 'syntax:documentation', 'syntax:punctuation'],
    },
    {
      id: 'visible-diagnostics',
      metric: 'apca',
      minimum: 55,
      roles: ['ui:status.error', 'ui:status.warning'],
    },
    {
      id: 'readable-independent-state-labels',
      metric: 'wcag',
      minimum: 4.5,
      roles: [
        'ui:status.error',
        'ui:status.warning',
        'ui:status.info',
        'ui:status.success',
        'terminal:ansi.red',
        'terminal:ansi.green',
        'terminal:ansi.yellow',
        'terminal:ansi.blue',
        'terminal:ansi.magenta',
        'terminal:ansi.cyan',
        'terminal:ansi.brightRed',
        'terminal:ansi.brightGreen',
        'terminal:ansi.brightYellow',
        'terminal:ansi.brightBlue',
        'terminal:ansi.brightMagenta',
        'terminal:ansi.brightCyan',
      ],
    },
  ],
  contrastPairs: [
    {
      id: 'button-label',
      foreground: 'ui:buttons.foreground',
      background: 'ui:buttons.background',
      minimum: 4.5,
    },
    {
      id: 'button-hover-label',
      foreground: 'ui:buttons.foreground',
      background: 'ui:buttons.hover.background',
      minimum: 4.5,
    },
    {
      id: 'badge-label',
      foreground: 'ui:badges.foreground',
      background: 'ui:badges.background',
      minimum: 4.5,
    },
    {
      id: 'focus-on-canvas',
      foreground: 'ui:accent.primary',
      background: 'ui:surface.canvas',
      minimum: 3,
    },
    {
      id: 'focus-on-field',
      foreground: 'ui:accent.primary',
      background: 'ui:surface.field',
      minimum: 3,
    },
    {
      id: 'focus-on-raised',
      foreground: 'ui:accent.primary',
      background: 'ui:surface.raised',
      minimum: 3,
    },
  ],
  stateComparisons: [
    {
      id: 'status-states',
      roles: ['ui:status.error', 'ui:status.warning', 'ui:status.success', 'ui:status.info'],
      pairing: 'all',
    },
    {
      id: 'bracket-depths',
      roles: [
        'brackets:depth1',
        'brackets:depth2',
        'brackets:depth3',
        'brackets:depth4',
        'brackets:depth5',
        'brackets:depth6',
      ],
      pairing: 'all',
    },
    {
      id: 'editor-overlay-states',
      roles: [
        'ui:editor.activeLine',
        'ui:editor.reference.read',
        'ui:editor.highlight',
        'vscode:editor.inactive.selection.background',
        'ui:editor.reference.write',
        'ui:search.match.passive',
        'ui:selection.primary',
        'ui:search.match.active',
      ],
      pairing: 'all',
    },
    {
      id: 'ansi-warm-states',
      roles: ['terminal:ansi.red', 'terminal:ansi.yellow', 'terminal:ansi.green'],
      pairing: 'adjacent',
    },
    {
      id: 'ansi-cool-states',
      roles: ['terminal:ansi.blue', 'terminal:ansi.magenta', 'terminal:ansi.cyan'],
      pairing: 'adjacent',
    },
    {
      id: 'ansi-bright-warm-states',
      roles: ['terminal:ansi.brightRed', 'terminal:ansi.brightYellow', 'terminal:ansi.brightGreen'],
      pairing: 'adjacent',
    },
    {
      id: 'ansi-bright-cool-states',
      roles: [
        'terminal:ansi.brightBlue',
        'terminal:ansi.brightMagenta',
        'terminal:ansi.brightCyan',
      ],
      pairing: 'adjacent',
    },
  ],
};

module.exports = themeSafetyContract;
