/** @type {import('../scripts/themeDefinition.mjs', { with: { 'resolution-mode': 'import' } }).ThemeOpacityContractSource} */
const themeOpacityContract = {
  opacities: {
    'ui:search.match.active': '70',
    'ui:search.match.passive': '3D',
    'ui:editor.highlight': '1F',
    'ui:editor.activeLine': '14',
    'ui:selection.primary': '5C',
    'ui:editor.reference.read': '1A',
    'ui:editor.reference.write': '2E',
    'ui:editor.bracket.matchBackground': '22',
    'ui:editor.bracket.matchBorder': 'D9',
    'ui:editor.predictive.background': '80',
    'ui:status.errorBackground': '24',
    'ui:status.infoBackground': '24',
    'ui:status.warningBackground': '24',
    'ui:status.modifiedBackground': '1C',
    'ui:status.successBackground': '1C',
    'ui:scrollbar.background': '50',
    'ui:scrollbar.hover.background': '7A',
    'ui:border.tab': 'FF',
    'terminal:selection': '55',
    'vscode:diff.editor.inserted.line.background': '14',
    'vscode:diff.editor.inserted.text.background': '26',
    'vscode:diff.editor.removed.line.background': '14',
    'vscode:diff.editor.removed.text.background': '26',
    'vscode:editor.hover.highlight.background': '22',
    'vscode:editor.inactive.selection.background': '26',
    'vscode:editor.word.highlight.border': '50',
    'vscode:editor.error.border': '00',
    'vscode:editor.hint.border': '00',
    'vscode:editor.info.border': '00',
    'vscode:editor.overviewRuler.addedForeground': '8C',
    'vscode:editor.overviewRuler.bracketMatchForeground': 'BF',
    'vscode:editor.overviewRuler.deletedForeground': '8C',
    'vscode:editor.overviewRuler.findMatchForeground': '60',
    'vscode:editor.overviewRuler.infoForeground': '8C',
    'vscode:editor.overviewRuler.selectionHighlightForeground': '78',
    'vscode:editor.overviewRuler.warningForeground': '8C',
    'vscode:editor.warning.border': '00',
    'vscode:merge.common.content.background': '1A',
    'vscode:merge.common.header.background': '33',
    'vscode:merge.current.header.background': '33',
    'vscode:merge.incoming.header.background': '33',
    'vscode:editor.minimapSlider.activeBackground': '60',
    'vscode:editor.minimapSlider.background': '40',
    'vscode:editor.minimapSlider.hoverBackground': '55',
    'vscode:preview.editor.match.highlight.background': '42',
    'vscode:scrollbar.active.background': '9F',
  },
  overrides: {
    light: {
      'ui:border.tab': '00',
    },
  },
};

module.exports = themeOpacityContract;
