$background = 030207
$onBackground = ded7ee
$surface = 030207
$surfaceDim = 030207
$surfaceBright = 21123e
$surfaceContainerLowest = 050309
$surfaceContainerLow = 07040d
$surfaceContainer = 100a1b
$surfaceContainerHigh = 150d29
$surfaceContainerHighest = 21123e
$onSurface = ded7ee
$surfaceVariant = 24134a
$onSurfaceVariant = b2a8c8
$inverseSurface = ded7ee
$inverseOnSurface = 030207
$outline = 6d5b8a
$outlineVariant = 24134a
$shadow = 000000
$scrim = 000000
$surfaceTint = 8652ff
$primary = 8652ff
$primaryDim = b48cff
$onPrimary = ffffff
$primaryContainer = 21123e
$onPrimaryContainer = ded7ee
$inversePrimary = 8050f0
$primaryFixed = d0b6ff
$primaryFixedDim = 8652ff
$onPrimaryFixed = 0c0c0c
$onPrimaryFixedVariant = 030207
$secondary = 4a7dff
$secondaryDim = 4a7dff
$onSecondary = ffffff
$secondaryContainer = 0c1126
$onSecondaryContainer = ded7ee
$secondaryFixed = 7da0ff
$secondaryFixedDim = 4a7dff
$onSecondaryFixed = 0c0c0c
$onSecondaryFixedVariant = 030207
$tertiary = c764ff
$tertiaryDim = 8652ff
$onTertiary = 0c0c0c
$tertiaryContainer = 1e133b
$onTertiaryContainer = ded7ee
$tertiaryFixed = d0b6ff
$tertiaryFixedDim = c764ff
$onTertiaryFixed = 0c0c0c
$onTertiaryFixedVariant = 030207
$error = e05270
$errorDim = e05270
$onError = ffffff
$errorContainer = 1f0c14
$onErrorContainer = ded7ee
$primaryPaletteKeyColor = 8652ff
$secondaryPaletteKeyColor = 4a7dff
$tertiaryPaletteKeyColor = c764ff
$neutralPaletteKeyColor = 6d5b8a
$neutralVariantPaletteKeyColor = 24134a
$errorPaletteKeyColor = e05270
$primary_paletteKeyColor = 8652ff
$secondary_paletteKeyColor = 4a7dff
$tertiary_paletteKeyColor = c764ff
$neutral_paletteKeyColor = 6d5b8a
$neutral_variant_paletteKeyColor = 24134a
$term0 = 120a1f
$term1 = e05270
$term2 = 39a96b
$term3 = d8893a
$term4 = 4a7dff
$term5 = 8652ff
$term6 = d7586e
$term7 = ded7ee
$term8 = 5a4a73
$term9 = f07a91
$term10 = 66c98d
$term11 = e3aa56
$term12 = 7da0ff
$term13 = d0b6ff
$term14 = ff7a90
$term15 = f0e9ff
$rosewater = f0e9ff
$flamingo = c764ff
$pink = d0b6ff
$mauve = 8652ff
$red = e05270
$maroon = f07a91
$peach = d8893a
$yellow = e3aa56
$green = 39a96b
$teal = d7586e
$sky = ff7a90
$sapphire = 4a7dff
$blue = 7da0ff
$lavender = d0b6ff
$klink = 4a7dff
$klinkSelection = 7da0ff
$kvisited = 8652ff
$kvisitedSelection = d0b6ff
$knegative = e05270
$knegativeSelection = f07a91
$kneutral = d8893a
$kneutralSelection = e3aa56
$kpositive = 39a96b
$kpositiveSelection = 66c98d
$text = ded7ee
$subtext1 = b2a8c8
$subtext0 = 6d5b8a
$overlay2 = 6d5b8a
$overlay1 = 7a679c
$overlay0 = 24134a
$surface2 = 21123e
$surface1 = 150d29
$surface0 = 100a1b
$base = 030207
$mantle = 07040d
$crust = 050309
$success = 39a96b
$onSuccess = 0c0c0c
$successContainer = 0a1714
$onSuccessContainer = ded7ee
