$background = 0a0910
$onBackground = d8d2e8
$surface = 0a0910
$surfaceDim = 0a0910
$surfaceBright = 2a203b
$surfaceContainerLowest = 0a0910
$surfaceContainerLow = 0f0d16
$surfaceContainer = 151320
$surfaceContainerHigh = 1d172b
$surfaceContainerHighest = 2a203b
$onSurface = d8d2e8
$surfaceVariant = 29233a
$onSurfaceVariant = d8d2e8
$inverseSurface = d8d2e8
$inverseOnSurface = 0a0910
$outline = 585269
$outlineVariant = 29233a
$shadow = 000000
$scrim = 000000
$surfaceTint = 965ef0
$primary = 965ef0
$primaryDim = b98aff
$onPrimary = ffffff
$primaryContainer = 2a203b
$onPrimaryContainer = d8d2e8
$inversePrimary = 382a52
$primaryFixed = b98aff
$primaryFixedDim = 965ef0
$onPrimaryFixed = 0c0c0c
$onPrimaryFixedVariant = 0a0910
$secondary = 5e7cd0
$secondaryDim = 5e7cd0
$onSecondary = ffffff
$secondaryContainer = 121321
$onSecondaryContainer = d8d2e8
$secondaryFixed = 82a6f4
$secondaryFixedDim = 5e7cd0
$onSecondaryFixed = 0c0c0c
$onSecondaryFixedVariant = 0a0910
$tertiary = b08bbc
$tertiaryDim = 965ef0
$onTertiary = 0c0c0c
$tertiaryContainer = 1c142c
$onTertiaryContainer = d8d2e8
$tertiaryFixed = b98aff
$tertiaryFixedDim = b08bbc
$onTertiaryFixed = 0c0c0c
$onTertiaryFixedVariant = 0a0910
$error = dd6b6b
$errorDim = dd6b6b
$onError = 0c0c0c
$errorContainer = 26161c
$onErrorContainer = d8d2e8
$primaryPaletteKeyColor = 965ef0
$secondaryPaletteKeyColor = 5e7cd0
$tertiaryPaletteKeyColor = b08bbc
$neutralPaletteKeyColor = 585269
$neutralVariantPaletteKeyColor = 29233a
$errorPaletteKeyColor = dd6b6b
$primary_paletteKeyColor = 965ef0
$secondary_paletteKeyColor = 5e7cd0
$tertiary_paletteKeyColor = b08bbc
$neutral_paletteKeyColor = 585269
$neutral_variant_paletteKeyColor = 29233a
$term0 = 272136
$term1 = dd6b6b
$term2 = 55a875
$term3 = d6a245
$term4 = 5e7cd0
$term5 = 965ef0
$term6 = 56a8b2
$term7 = d8d2e8
$term8 = 6a627f
$term9 = ea7a7a
$term10 = 68ba8a
$term11 = e3b75d
$term12 = 82a6f4
$term13 = b98aff
$term14 = 68b9c2
$term15 = f0eaf8
$rosewater = f0eaf8
$flamingo = b08bbc
$pink = b98aff
$mauve = 965ef0
$red = dd6b6b
$maroon = ea7a7a
$peach = d6a245
$yellow = e3b75d
$green = 55a875
$teal = 56a8b2
$sky = 68b9c2
$sapphire = 5e7cd0
$blue = 82a6f4
$lavender = b98aff
$klink = 5e7cd0
$klinkSelection = 82a6f4
$kvisited = 965ef0
$kvisitedSelection = b98aff
$knegative = dd6b6b
$knegativeSelection = ea7a7a
$kneutral = d6a245
$kneutralSelection = e3b75d
$kpositive = 55a875
$kpositiveSelection = 68ba8a
$text = d8d2e8
$subtext1 = d8d2e8
$subtext0 = 585269
$overlay2 = 585269
$overlay1 = 6a627f
$overlay0 = 29233a
$surface2 = 2a203b
$surface1 = 1d172b
$surface0 = 151320
$base = 0a0910
$mantle = 0f0d16
$crust = 0a0910
$success = 55a875
$onSuccess = 0c0c0c
$successContainer = 111719
$onSuccessContainer = d8d2e8
